### ISSUE TITLE
Error when trying to Deploy

### ISSUE THREAD

**Issue by slugger9066** [scott113341/southwest-price-drop-bot#15]
Hi there, after I enter all of the config variables and hit Deploy, I'm receiving the following error.

Error: "Item could not be created: Unknown Error. Please contact support."

Any assistance is truly appreciated.

Thank you!

**Comment by SkydiverMedic** [comment]
Having the exact same issue. Thanks to anyone who is able to help - not sure what to do with this vague error.

**Comment by Wolfe1** [comment]
Same issue here :(

**Comment by Wolfe1** [comment]
Problem seems to have resolved itself today.

**Comment by scott113341** [comment]
I've also run into transient issues before when using the Deploy to Heroku button.  Consistent with your experience, I've always been able to employ the powerful technique of "keep trying until it works".  My guess is this is something on Heroku's end, since I've experienced this on other projects as well.
