### ISSUE TITLE
No Text

### ISSUE THREAD

**Issue by rusd11** [scott113341/southwest-price-drop-bot#9]
I'm not receiving a text when the price is below the _Alert Threshold_. I do see the Victory Chart being displayed, setup the Heroku Scheduler and setup my Plivo account. Do we need to have a **paid** Plivo account for this to work? @scott113341 
This looks really great, I currently use https://github.com/ezekg/swa-dashboard, but I really like this web-based solution!

**Comment by scott113341** [comment]
Hi @rusd11, yes, you'll need a number provisioned from paid Plivo account.  I realize this is really bad because, honestly, who the heck has a Plivo account?  I chose it because it's cheaper than Twilio and I'm cheap.

This is something I've been thinking about for a while, I just opened #10 to formalize the request.  Ideally, I want people to be able to effortlessly set up notifications via whatever channel they want, whether that's text, email, slack, etc.  I'll give this some thought this coming week.

**Comment by rusd11** [comment]
Ah, interesting, I'll go ahead and buy a number. I know with Twilio you can get a free number and send SMS using that number to your sandbox numbers using only a trial account, but know that the overall costs seem to be higher with Twilio when there is a high volume of usage.
Thanks @scott113341

**Comment by rusd11** [comment]
I'll close this since it's not an issue. Thanks for the help, also the redesign looks great!
